### ISSUE TITLE
Failed to initialize MeCab. Runitme Error in version 1.0.2

### ISSUE THREAD

**Issue by prb2307** [ikegami-yukino/mecab#11]
Hello! I am getting this error on Windows 10.
Python version - 3.6

The default output parameter works fine but the other parameters like "Ochasen" do not work.
Could you please help me in figuring it out?
Thanks.

`m = MeCab.Tagger("-Ochasen")`
```

------------------- ERROR DETAILS ------------------------
arguments: -Ochasen
error message:  [!tmp.empty()] unknown format type [chasen]
----------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ts-prashant.bansod\Python\Python36\lib\site-packages\MeCab\__init__.py", line 124, in __init__
    super(Tagger, self).__init__(args)
RuntimeError
```

**Comment by polm** [comment]
Based on your error output you are using `mecab-python3`, not the package in this repository. I think you already realized that because you filed the issue below. You should close this issue, since this repository is not related. 

https://github.com/SamuraiT/mecab-python3/issues/59

**Comment by prb2307** [comment]
> Based on your error output you are using `mecab-python3`, not the package in this repository. I think you already realized that because you filed the issue below. You should close this issue, since this repository is not related.
> 
> [SamuraiT/mecab-python3#59](https://github.com/SamuraiT/mecab-python3/issues/59)

Thank you very much
