### ISSUE TITLE
Pip installation is broken?

### ISSUE THREAD

**Issue by agirbau** [ikegami-yukino/mecab#17]
Hello!
I was trying to install the repo packages with `pip install mecab`.

Logs:
    Complete output (10 lines):
    /bin/sh: 1: mecab-config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dt4w1bl9/mecab/setup.py", line 53, in <module>
        include_dirs=cmd2("mecab-config --inc-dir"),
      File "/tmp/pip-install-dt4w1bl9/mecab/setup.py", line 19, in cmd2
        return cmd1(strings).split()
      File "/tmp/pip-install-dt4w1bl9/mecab/setup.py", line 15, in cmd1
        return os.popen(strings).readlines()[0].rstrip()
    IndexError: list index out of range

**Comment by ikegami-yukino** [comment]
@agirbau 
What OS are you using?
Did you install mecab with mecab-config?

**Comment by devsteppe9** [comment]
```
#7 38.04 Collecting mecab==0.996.3
#7 38.08   Downloading mecab-0.996.3.tar.gz (62 kB)
#7 38.13      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 KB 2.5 MB/s eta 0:00:00
#7 38.21   Preparing metadata (setup.py): started
#7 40.07   Preparing metadata (setup.py): finished with status 'error'
#7 40.16   error: subprocess-exited-with-error
#7 40.16   
#7 40.16   × python setup.py egg_info did not run successfully.
#7 40.16   │ exit code: 1
#7 40.16   ╰─> [11 lines of output]
#7 40.16       /bin/sh: mecab-config: command not found
#7 40.16       Traceback (most recent call last):
#7 40.16         File "<string>", line 2, in <module>
#7 40.16         File "<pip-setuptools-caller>", line 34, in <module>
#7 40.16         File "/tmp/pip-install-ji2gx4lu/mecab_138336d9f1e8434a9656707ba343cfb6/setup.py", line 53, in <module>
#7 40.16           include_dirs=cmd2("mecab-config --inc-dir"),
#7 40.16         File "/tmp/pip-install-ji2gx4lu/mecab_138336d9f1e8434a9656707ba343cfb6/setup.py", line 19, in cmd2
#7 40.16           return cmd1(strings).split()
#7 40.16         File "/tmp/pip-install-ji2gx4lu/mecab_138336d9f1e8434a9656707ba343cfb6/setup.py", line 15, in cmd1
#7 40.16           return os.popen(strings).readlines()[0].rstrip()
#7 40.16       IndexError: list index out of range
#7 40.16       [end of output]
#7 40.16   
#7 40.16   note: This error originates from a subprocess, and is likely not a problem with pip.
#7 40.19 error: metadata-generation-failed
#7 40.19 
#7 40.19 × Encountered error while generating package metadata.
#7 40.19 ╰─> See above for output.
```


Same issue here. 
While installing docker image below, basically OS is linux.

`FROM public.ecr.aws/lambda/python:3.8`

**Comment by ikegami-yukino** [comment]
@Jaha96 
This problem is that MeCab C++ library is not installed.
Because this Python module is the wrapper of MeCab C++ library.

**Comment by devsteppe9** [comment]
Thanks a lot! I got my solution.

**Comment by devanghingu** [comment]
i jut solved this issue by installing `mecab, mecab-ipadic-utf8` and `libmecab-dev` at system level through Advanced package tool :+1:
